ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'pending';
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS last_error TEXT NULL;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS failed_at TIMESTAMP NULL;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS processed_at TIMESTAMP NULL;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS max_attempts INT NOT NULL DEFAULT 3;

CREATE INDEX ce_jobs_status_queue_available_idx ON ce_jobs(status, queue, available_at);
