ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS status VARCHAR(40) NOT NULL DEFAULT 'pending';
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS last_error TEXT NULL;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS failed_at TIMESTAMPTZ NULL;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ NULL;
ALTER TABLE ce_jobs ADD COLUMN IF NOT EXISTS max_attempts INT NOT NULL DEFAULT 3;

CREATE INDEX IF NOT EXISTS ce_jobs_status_queue_available_idx ON ce_jobs(status, queue, available_at);
