<?php

declare(strict_types=1);

return [
    'site' => [
        'name' => 'Cajeer',
        'domain' => 'https://cajeer.ru',
        'language' => 'ru',
        'founded' => 2014,
        'founder' => 'SkiF4er',
        'copyright' => '© Cajeer',
        'tagline' => 'Экосистема проектов и брендов',
        'description' => 'Официальный сайт Cajeer — экосистемы проектов и брендов, основанной в 2014 году SkiF4er.',
        'theme_color' => '#0b0f19',
        'logo' => 'img/logo.png',
        'favicon' => 'img/favicon-32.png',
        'social_preview' => 'img/social-preview.png',
        'social_image_width' => 1200,
        'social_image_height' => 630,
        'asset_version' => '20260420-2',
    ],
    'brand' => [
        'founder' => 'SkiF4er',
        'public_voice' => 'Cajeer не ведёт публичной коммуникации как организация. Единственным публичным представителем является SkiF4er.',
        'remote_model' => 'Cajeer — полностью удалённая команда без офиса и штаб-квартиры. Все сотрудники работают удалённо.',
        'non_disclosure' => [
            'Доходы и прибыль не публикуются.',
            'Численность команды и внутренняя структура не раскрываются.',
            'Инфраструктура, серверы и внутренние системы не описываются публично.',
        ],
    ],
    'support' => [
        'email' => 'support@cajeer.ru',
        'telegram_bot' => 'https://t.me/CajeerBot',
        'telegram_channel' => 'https://t.me/Cajeer',
        'discord_server' => 'https://discord.gg/QmJ2NDkzYv',
        'public_representative' => 'https://t.me/SF4Blog',
    ],
    'principles' => [
        'Строгий контроль публичной коммуникации.',
        'Минимальное раскрытие внутренних процессов и структуры.',
        'Поддержка пользователей всех публичных проектов через единые каналы Cajeer.',
        'Удалённая модель работы без офиса и штаб-квартиры.',
        'Все ресурсы и проекты Cajeer ориентированы на русский язык.',
    ],
    'project_status_labels' => [
        'official' => 'Официальный проект',
        'announced' => 'Анонсированный проект',
        'active' => 'Активный проект',
    ],
    'projects' => [
        'nevermine' => [
            'name' => 'NeverMine',
            'slug' => 'nevermine',
            'short_description' => 'Официально анонсированный проект экосистемы Cajeer.',
            'description' => 'NeverMine — официальный проект экосистемы Cajeer, размещённый в публичном перечне анонсированных проектов.',
            'public_note' => 'Публичная страница проекта размещена в официальном представительском контуре Cajeer.',
            'status' => 'official',
            'order' => 10,
            'is_featured' => true,
            'external_url' => null,
            'meta_title' => 'NeverMine — проект Cajeer',
            'meta_description' => 'NeverMine — официальный проект экосистемы Cajeer.',
            'updated_at' => '2026-04-20',
        ],
        'candyrp' => [
            'name' => 'CandyRP',
            'slug' => 'candyrp',
            'short_description' => 'Официально анонсированный проект экосистемы Cajeer.',
            'description' => 'CandyRP — официальный проект экосистемы Cajeer, размещённый в публичном перечне анонсированных проектов.',
            'public_note' => 'Публичная страница проекта размещена в официальном представительском контуре Cajeer.',
            'status' => 'official',
            'order' => 20,
            'is_featured' => true,
            'external_url' => null,
            'meta_title' => 'CandyRP — проект Cajeer',
            'meta_description' => 'CandyRP — официальный проект экосистемы Cajeer.',
            'updated_at' => '2026-04-20',
        ],
    ],
    'navigation' => [
        '/' => 'Главная',
        '/about' => 'О Cajeer',
        '/team' => 'Команда',
        '/projects' => 'Проекты',
        '/support' => 'Поддержка',
        '/brand' => 'Бренд',
    ],
    'meta' => [
        'home' => ['title' => 'Cajeer — экосистема проектов и брендов', 'description' => 'Официальный сайт Cajeer — экосистемы проектов и брендов, основанной в 2014 году SkiF4er.', 'updated_at' => '2026-04-20'],
        'about' => ['title' => 'О Cajeer', 'description' => 'Информация о Cajeer: основание, модель работы, публичная позиция и принципы.', 'updated_at' => '2026-04-20'],
        'team' => ['title' => 'Cajeer Team', 'description' => 'Cajeer Team — команда управления проектами и брендами экосистемы.', 'updated_at' => '2026-04-20'],
        'projects' => ['title' => 'Проекты', 'description' => 'Официально анонсированные проекты экосистемы Cajeer.', 'updated_at' => '2026-04-20'],
        'support' => ['title' => 'Поддержка', 'description' => 'Единые каналы поддержки пользователей проектов и брендов Cajeer.', 'updated_at' => '2026-04-20'],
        'brand' => ['title' => 'Бренд Cajeer', 'description' => 'Официальная информация о бренде Cajeer и правилах публичного представления.', 'updated_at' => '2026-04-20'],
        '404' => ['title' => 'Страница не найдена', 'description' => 'Запрошенная страница сайта Cajeer не найдена.', 'updated_at' => '2026-04-20'],
    ],
];
